### ISSUE TITLE
Empty preview image for documents (e.g PDF) in AreaBrick Dwonloads

### ISSUE THREAD

**Issue by buezu09** [dachcom-digital/pimcore-toolbox#141]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Preview images for documents (e.g. PDF) are not generated in the AreaBrick Download although the option «Show preview images» is activated. $download->getImageThumbnail($previewThumbName) in «DonwloadExtension.php»
<img width="396" alt="Bildschirmfoto 2020-07-02 um 08 26 17" src="https://user-images.githubusercontent.com/8806978/86323784-bdb4ef80-bc3d-11ea-9c90-c9ca4ae55718.png">
 returns an empty preview image.

**Comment by solverat** [comment]
Hey @buezu09. I guess you missed some important preparations.

1. Make sure libreoffice is installed on your system (This is a default optional dependency in pimcore and so does toolbox):
![image](https://user-images.githubusercontent.com/700119/97994718-e284c380-1de5-11eb-92c8-853684ab8364.png)

2. Make sure that your maintenance mode is active since image thumbnail processing also runs asynchronously (Quick command: `bin/console pimcore:maintenance -j asset_document_convert`).

3. Make sure you have all required image thumbnails (toolbox default preview thumbnail name is `downloadPreviewImage`)
